theme = "current"
# primary = #1793d1
# accent = #66d9ff

[themes]
  [themes.current]
  # primary color
  selector = { fg = "#9d4edd" }
  tab_marker = {  fg = "#9d4edd" }
  volume_filled = { fg = "#9d4edd" }
  meter_active = { fg = "#9d4edd" }
  meter_center_active = { fg = "#9d4edd" }
  dropdown_border = { fg = "#9d4edd" }

  # accent color
  dropdown_selected  = { fg = "#c77dff", add_modifier = "REVERSED" }
  tab_selected = { fg = "#c77dff" }
